apiVersion: v1
kind: Namespace
metadata:
  name: capstone-ns
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: capstone-quota
  namespace: capstone-ns
spec:
  hard:
    pods: "10"
    requests.cpu: "4"
    requests.memory: 2Gi
    limits.cpu: "8"
    limits.memory: 4Gi
