apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: capstone-ns
type: Opaque
stringData:
  DB_USER: "postgres"
  DB_PASSWORD: "securepassword123" # Use a stronger password in production
