apiVersion: v1
kind: Service
metadata:
  name: capstone-service
  namespace: capstone-ns
spec:
  selector:
    app: capstone-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
